= Metamorph - TYPO3 CMS to TYPO3 Flow converter
Martin Helmich <m.helmich@mittwald.de>
2014-12-23
:source-highlighter: coderay
:icons: font
:toc:

CAUTION: This package is currently unter heavy development and by no means
stable! APIs and behaviour can change at any point without notice.

== Synopsis

Metamorph is a tool intended for converting TYPO3 sites into TYPO3 Flow
applications and (later) TYPO3 Neos sites.

== Installation

Metamorph is a TYPO3 Flow package. Currently, the best way to install it is to
use the https://github.com/mittwald/flow-distribution-metamorph[distribution package],
using http://getcomposer.org[Composer].

Alternatively, you can require it using composer:

[source,json]
----
{
    "require": {
        "mittwald-typo3/flow-metamorph": "*"
    }
}
----

== Features (current)

- Convert Extbase extensions into TYPO3 Flow packages. This includes:
    
    * Rewriting non-namespaced classes to namespaced classes
    * Replace Extbase classes with their TYPO3 Flow counterparts, where possible
      and provide compatibility classes otherwise
    * Replace Extbase annotations (like `@inject`) the respective Flow annotations
      (like `@Flow\Inject`), including namespace import.
    * Enrich Extbase domain models with annotations for the Doctrine2 ORM
      framework.
    * Translate locallang XML files to XLIFF.
    * Create Doctrine migrations for converted entity classes.
    * Option to keep the existing database structure

- Convert pibase extensions into TYPO3 Flow packages. This includes:

    * Rewriting non-namespaced classes to namespaced classes

== Features (planned)

- More features for Extbase migration:

    * _(add custom wishes here)_

- Convert pibase extensions into TYPO3 Flow packages. This includes:

    * Rewrite classes to use TYPO3 Flow APIs where possible, and provice
      compatibility classes otherwise
    * Generate controller classes wrapping the migrated plugin classes

- Convert plugins (both Extbase and piBase) into TYPO3 Neos plugins.

- Convert TYPO3's page tree into the TYPO3 Neos content repository format

== Further reading

- link:Documentation/GettingStarted.adoc["Getting started" guide]
- link:Documentation/TechnicalManual.adoc[In-depth technical manual]

