<?php
namespace Mw\Metamorph\Transformation\RewriteNodeVisitors;

/*                                                                        *
 * This script belongs to the TYPO3 Flow package "Mw.Metamorph".          *
 *                                                                        *
 * (C) 2014 Martin Helmich <m.helmich@mittwald.de>                        *
 *          Mittwald CM Service GmbH & Co. KG                             *
 *                                                                        */

use Mw\Metamorph\Transformation\Helper\CommentHelper;
use PhpParser\Node;
use TYPO3\Flow\Annotations as Flow;

/**
 * Visitor class that replaces extension keys in redirect calls.
 *
 * This visitor replaces extension keys that are used in redirect calls with
 * the respective package names.
 *
 * Example::
 *
 *     // Before
 *     $this->redirect('action', 'MyController', 'my_extension');
 *
 *     // After
 *     $this->redirect('action', 'MyController', 'My.Package');
 *
 * When a non-NULL expression is used as extension key, this transformation will
 * insert a lookup construct here
 *
 * Example::
 *
 *     // Before
 *     $this->redirect('action', 'MyController', magicFunction());
 *
 *     // After
 *     $metamorphExtensions = ['my_extension' => 'My.Package'];
 *     $this->redirect('action', 'MyController', $metamorphExtensions[magicFunction()]);
 *
 * @package    Mw\Metamorph
 * @subpackage Transformation\RewriteNodeVisitors
 */
class PackageRedirectVisitor extends AbstractControllerVisitor {

	/**
	 * @var CommentHelper
	 * @Flow\Inject
	 */
	protected $commentHelper;

	/**
	 * Called when the visitor leaves a node inside an ActionController.
	 *
	 * @param Node $node The node to process
	 * @return array|null|Node The node replacement
	 */
	public function leaveControllerNode(Node $node) {
		if ($node instanceof Node\Expr\MethodCall) {
			$var  = $node->var;
			$name = $node->name;

			$isRedirect =
				($var instanceof Node\Expr\Variable) &&
				($var->name == 'this') &&
				$name == 'redirect';

			if ($isRedirect && count($node->args) >= 3) {
				$extensionKey    = $node->args[2];
				$packageMappings = $this->configuration->getPackageMappingContainer();

				if ($extensionKey->value instanceof Node\Scalar\String) {
					$extensionKeyValue = $extensionKey->value->value;
					$packageMapping    = $packageMappings->getPackageMapping($extensionKeyValue);

					if ($packageMapping) {
						$node->args[2]->value = new Node\Scalar\String($packageMapping->getPackageKey());
						return $node;
					} else {
						return $this->commentHelper->addCommentToNode(
							$node,
							'@todo: No Flow package found for TYPO3 extensions "' . $extensionKeyValue . '"!'
						);
					}
				} elseif ($extensionKey->value instanceof Node\Expr\ConstFetch && $extensionKey->value->name == 'NULL') {
					return NULL;
				} else {
					$arrayItems = [];

					foreach ($packageMappings->getPackageMappings() as $packageMapping) {
						$arrayItems[] = new Node\Expr\ArrayItem(
							new Node\Scalar\String($packageMapping->getPackageKey()),
							new Node\Scalar\String($packageMapping->getExtensionKey())
						);
					}

					$arrayNode       = new Node\Expr\Array_($arrayItems);
					$variableNode    = new Node\Expr\Variable('metamorphPackages');
					$arrayAssignment = new Node\Expr\Assign($variableNode, $arrayNode);

					$arrayDereference     = new Node\Expr\ArrayDimFetch($variableNode, $extensionKey->value);
					$node->args[2]->value = $arrayDereference;

					$this->commentHelper->addCommentToNode(
						$arrayAssignment,
						'@todo: This mapping was automatically generated by Metamorph. Please check for correctness.'
					);

					return [$arrayAssignment, $node];
				}
			}
		}

		return NULL;
	}
}