= Metamorph transformation reference
Martin Helmich <m.helmich@mittwald.de>
2015-01-11
:source-highlighter: coderay
:icons: font
:toc:

.Indended audience, prerequisites and learning goals
****
You should read this document, when:

- You want to understand what Metamorph actually does when migrating TYPO3 CMS extensions
- You want to debug errors that occured when executing a migration

Before reading this document, you should have knowledge of:

- TYPO3 Flow basics (package structure, developing packages)
- Metamorph basics (see the link:GettingStarted.adoc["Getting started" guide])
- How Metamorph works with transformations (read the appropriate section of the link:TechnicalManual.adoc[technical manual]).
- A rough understanding on how source code is parsed and what an _abstract syntax tree_ is.

After reading this document, you will:

- Unterstand exactly what happens when executing a migration
****

== Existing transformations

=== Building the package map

The `Mw\Metamorph\Step\ExtensionInventory` step should be the first transformation to be executed (although it does not actually transform anything, yet). It will perform the following actions:

- Go into the source directory of the current morph configuration (remember, the source directory is the root directory of a TYPO3 CMS installation) and scan the `typo3conf/ext` directory for TYPO3 extensions.
- Apply the _extension matcher_ (see <<Extension selection>> for more information) of the current configuration *on each extension* to check whether the extension should be migrated to the current TYPO3 Flow installation.
- For each extension that should be migrated:

  * Try to guess a good TYPO3 Flow package key (and yes, this is actually mostly guesswork!). This is done using the following algorithm (pseudocode):
+
[source,java]
----
extensionKey
  .split('_')
  .map((word : string) => word.firstLetterToUppercase())
  .join('.')
----
+
NOTE: This algorithm is not optimal! It will not always generate valid package keys, so sometimes, manual adjustments may be necessary. See the explanation box below for more information.

  * Extract metadata (like description and author information) from the TYPO3 extension's `ext_emconf.php` file.

  * Create a new package mapping from the TYPO3 extension.

.On package name generation
****

As you may have noticed, the automatic package name generation does not produce optimal results in all cases. In some cases, manual adjustments might be necessary. Metamorph will try to warn you about invalid or otherwise dangerous package names. However, while these are easy to find, they are difficult to fix automatically, so some manual adjustments might be needed.

The table below contains some examples on how extension keys are converted to package keys (along with some typical pitfalls):

|===
|Extension key |Package key |Remarks

|`mw_example`
|`Mw.Example`
|Valid! Yay!

|`example`
|`Example`
|Invalid, no vendor prefix

|`mw_example_advanced`
|`Mw.Example.Advanced`
|Valid per se, but PSR-0 namespaces overlap with `Mw.Example`
|===

****

=== Building the class map

The `Mw\Metamorph\Step\ClassInventory` step should be executed *after* the package map generation. It will perform the following actions:

- *For each* package from the package mapping,

  * Find all PHP files. Parse the PHP files and look for class definitions.
  * *For each PHP class*, use the package name and try to generate a class name that fits into the PSR-0 prefix of the package namespace.
  * Create a new class mapping for each PHP class.

.On class name generation
****
Metamorph tries to automatically determine a class name (and namespace) that fits into the PSR-0 namespace root of the containing package. This usually works well for Extbase classes that follow certain conventions, but is mainly guesswork for pibase extensions that are named without any fixed conventions. There are some special rules for plugin classes (like `tx_<extkey>_pi1`), though. Consider the following table for some examples on generated class names (the root namespace is `Mw\Example` in all cases):

|===
|Old class name |New class name |Remarks

|`Mw\MwExample\Controller\FooController`
|`Mw\Example\Controller\FooController`
|

|`Tx_MwExample_Controller_FooController`
|`Mw\Example\Controller\FooController`
|

|`tx_mwexample_pi1`
|`Mw\Example\Plugin\Pi1`
| You should rename that one! `Pi1` is not a good class name.
|===

****

=== Building the resource map

The `Mw\Metamorph\Step\ResourceInventory` step should be executed *after* the package map generation. It will perform the following actions:

- *For each* package from the package mapping,

  * Find all resource files. Files are found by their *file extension*.
  * Determine where the file should be stored in the migrated TYPO3 Flow package. While Extbase extensions follow the same pattern as Flow packages (with a `Resources/` directory and `Private` and `Public` subdirectories), in pibase extensions, resource files can actually be found anywhere. By default, Metamorph will try to categorize found resource files by their extension into groups and then move these into respective subdirectories.
+
This is entirely configurable. The entire resource mapping is stored in the `Mw.Metamorph.resourceExtensions` setting:
+
.Definition of resource mappings in the package settings
[source,yaml]
----
Mw:
  Metamorph:
    resourceExtensions:
      templates:
        targetPath: Private/Templates
        extensions: [html, htm]
      languageFiles:
        targetPath: Private/Language
        extensions: [xml, xlf]
      images:
        targetPath: Public/Images
        extensions: [jpeg, jpg, gif, tif, svg, eps, png]
      javascript:
        targetPath: Public/JavaScript
        extensions: [js, coffee, ts]
      css:
        targetPath: Public/Stylesheets
        extensions: [css, sass, less, scss]
----

=== Clean up packages

When you are migrating continuously, it is entirely possible that your local TYPO3 Flow instance already contains some of the packages that would be created during migration. This step, modelled by the class `Mw\Metamorph\Step\CleanupPackages`, will clean up each target package so that migration is easily possible:

. If you are using a source control system like Git, Metamorph will checkout the `metamorph` branch before actually doing anything. When the migration was completed, Metamorph will try to merge the `metamorph` branch back into your `master` branch.
. Otherwise, Metamorph will delete the package and have the next transformation step re-create it.

=== Create packages

The `Mw\Metamorph\Step\CreatePackages` step will now create all TYPO3 Flow packages that are specified in the _package mapping_. For this, Metamorph will use TYPO3 Flow's http://typo3.org/api/flow/TYPO3/Flow/Package/class-PackageManager.html[APIs for package management]:

[source,php]
----
foreach ($packageMappingContainer->getPackageMappings() as $packageMapping) {
    if (FALSE === $this->packageManager->isPackageAvailable($packageMapping->getPackageKey())) {
        $this->packageManager->createPackage(
            $packageMapping->getPackageKey(),
            $this->createPackageMetaData($packageMapping),
            NULL,
            'typo3-flow-package'
        );
    }
}
----

The package meta data (description, authors) will be migrated from the source extension.

=== Migrate classes and resources

These are actually two steps: `Mw\Metamorph\Step\CreateClasses` and `Mw\Metamorph\Step\CreatePackages`. Each of these steps walks the _class mapping_ (or _resource mapping_, respectively) and copies each file to the target location in the new TYPO3 Flow site.

Classes are stored in the target package's _Classes/_ directory according to their class name (this is required, because they need to be auto-loadable). Resource files are simply placed in the target directory that is specified in the _resource mapping_.

=== Rename classes

This step renames all classes that were copied in the previous step according to the _class mapping_ configuration. The PHP class for this transformation is actually generic (`Mw\Metamorph\Transformation\GenericAstVisitorTransformation`) and is used again in later steps. This transformation class does the following:

[options="compact"]
. Parse each PHP class file into a syntax tree
. Traverse the syntax tree and apply a configurable set of node visitors
. Dump the modified syntax tree back into the target file

See <<Modifying source code inside transformations>> for more information.

In this case, this transformation step specifically does the following:

. Resolve class imports. This means that everytime, a class is imported with a `use` statement and then used with its relative name somewhere in the code, this usage will simply be replaced with the fully-qualified class name.
+
[cols="1a,1a"]
|===
|Before | After

|

[source,php]
----
use Foo\Bar;
use Bar\Baz;

class Baz extends Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new Baz();
    }
}
----

|

[source,php]
----
use Foo\Bar;
use Bar\Baz;

class Baz extends \Foo\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Bar\Baz();
    }
}
----
|===
+
. For each class definition, look for the fully-qualified class name in the _class mapping_. Then replace the class definition with the new class name. When the class definition is inside a namespace statement, change the namespace name accordingly. When the class definition is **not inside a namespace statement**, wrap the entire file in a namespace statement according to the new class name.
+
[cols="1a,1a"]
|===
|Before | After

|

[source,php]
----
class Old_Baz extends \Foo\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Bar\Baz();
    }
}
----

|

[source,php]
----
namespace New;
class UberBaz extends \Foo\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Bar\Baz();
    }
}
----

|

[source,php]
----
namespace Old;
class Baz extends \Foo\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Bar\Baz();
    }
}
----

|

[source,php]
----
namespace New;
class UberBaz extends \Foo\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Bar\Baz();
    }
}
----

|===
+
. For each **class usage** like constructor calls, static method calls, inheritance and constant usages, replace the class name when a class mapping is defined.
+
[cols="1a,1a"]
|===
|Before | After

|

[source,php]
----
namespace New;
class Baz extends \Old\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \Old\Baz();
    }
}
----

|

[source,php]
----
namespace New;
class Baz extends \New\Bar {
    protected $foo;
    public function __construct() {
        $this->baz = new \New\Baz();
    }
}
----
|===
+
. Look for the class name in strings and doc comments. Replace the class name when a class mapping for this class is defined.
+
[cols="1a,1a"]
|===
|Before | After

|

[source,php]
----
namespace New;
class Baz extends \New\Bar {
    /** @var \Old\Baz */
    protected $foo;
    public function __construct() {
        $class = "Old\\Baz";
        $this->baz = new $class();
    }
}
----

|

[source,php]
----
namespace New;
class Baz extends \New\Bar {
    /** @var \New\Baz */
    protected $foo;
    public function __construct() {
        $class = "New\\Baz";
        $this->baz = new $class();
    }
}
----
|===


=== Analyzing the class definitions

The `Mw\Metamorph\Step\AnalyzeClasses` step will iterate over each class from the _class mapping_ and analyze the class' inheritance structure and properties. This information is then stored in the _class definition container_. See <<Using the class definition container>> for more information on the _class definition container_.

=== Refactorings

This is the main transformation step. It uses the `Mw\Metamorph\Transformation\GenericAstVisitorTransformation` class already introduced in <<Rename classes>>. This step applies a number of transformation visitors to the syntax tree of each class. The following list briefly outlines the purpose of each node visitor (all classnames in the `Mw\Metamorph\Step\TransformationVisitor` namespace):

ExtbaseClassReplacementVisitor::
    Replaces extbase classes with their TYPO3 Flow equivalents. An example would be the `TYPO3\CMS\Extbase\Mvc\Controller\ActionController` class which is replaced by the `TYPO3\Flow\Mvc\Controller\ActionController` class. The classes that should be replaced can be configured in the configuration setting `Mw.Metamorph.staticReplacements`.

EntityDoctrineMigrationVisitor::
    Migrates entity and value object classes to _Doctrine_. This affects all classes that (*directly or indirectly*) inherit `TYPO3\CMS\Extbase\DomainObject\AbstractEntity` or `TYPO3\CMS\Extbase\DomainObject\AbstractValueObject` (or their legacy `Tx_`-style equivalents). Classes that directly inherit one of these classes will have this inheritance removed, as Doctrine works with plain objects. Instead, appropriate `@Flow\Entity` annotations will be added.
+
IMPORTANT: Metamorph will convert Extbase value objects (inheriting `TYPO3\CMS\Extbase\DomainObject\AbstractValueObject`) to *entity classes*. The reason for this is that Flow puts much stricter constraints on value objects than Extbase. For example, value objects must be truly *immutable* in Flow (all properties need to be set using constructor arguments, and setter methods are not allowed). Extbase is much more lenient on this and actually allows value objects to be mutable. Because of this, it makes more sense to convert them into entities, instead.

ReplaceMakeInstanceCallsVisitor::
    This visitor replaces calls to `TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance`. For singleton objects (these always implement the `TYPO3\CMS\Core\SingletonInterface`), these calls are replaced with a dependency injection. For prototype-scoped objects, the `makeInstance` call is replaced by a simple constructor call.
+
.Example: Simple string argument, prototype-scoped
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
class Foo {
  public function foo() {
    $bar = t3lib_div::makeInstance('Bar');
  }
}
----
|
[source,php]
----
class Foo {
  public function foo() {
    $bar = new Bar();
  }
}
----
|===
+
.Example: Simple string argument, singleton-scoped
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
class Foo {
  public function foo() {
    $bar = t3lib_div::makeInstance('Bar');
  }
}
----
|

[source,php]
----
class Foo {
  /** @var Bar
    * @Flow\Inject */
  protected $bar;
  public function foo() {
    $bar = $this->bar;
  }
}
----

|===
+
.Example: Complex expression argument, prototype-scoped
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
class Foo {
  public function foo($baz) {
    $bar = t3lib_div::makeInstance(
      $baz . 'Object', 123);
  }
}
----
|

[source,php]
----
class Foo {
  public function foo($baz) {
    $_b7c620c5 = $baz . 'Object'; // <1>
    $bar = new $_b7c620c5(123);
  }
}
----
<1> A temporary variable is really necessary here. The expression `$bar = new $baz . 'Object'()` is syntactically *really* wrong.

|===
+
.Example: Complex expression argument, singleton-scoped
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
class Foo {
  public function foo($baz) {
    $bar = t3lib_div::makeInstance(
      $baz . 'Object');
  }
}
----
|

[source,php]
----
class Foo {
  /** @var ObjectManager
   *  @Flow\Inject */
  protected $objectManager;
  public function foo($baz) {
    $bar = $this->objectManager->get(
      $baz . 'Object');
  }
}
----

|===
+
RewriteSingletonsVisitor::
    This visitor affects all classes that implement the `TYPO3\CMS\Core\SingletonInterface` interface (or its legacy variant `t3lib_Singleton`). The interface implementation will be removed, and a `@Flow\Scope("singleton")` annotation added to the class.

ReplaceAnnotationsVisitor::
    This visitor replaces all Extbase annotations with their Flow equivalents; this is mostly search&replace (for example `@inject` becomes to `@Flow\Inject`). Some annotations require some more logic; for example `@validate StringLength(minLength=3)` needs to be converted to `@Flow\Validate(type="StringLength", options={"minLength"=3})`. Currently, these replacements are hardcoded in the `ReplaceAnnotationsVisitor` class. Have a look there for more information.

InjectUtilitiesVisitor::
    This visitor replaces all kinds of utility calls (most prominently the infamous `GeneralUtility` class). Although Metamorph does provide a compatibility layer for these classes (actually, the package `Mw.T3Compat` does), these classes do not allow their methods to be called statically. This is because the compatibility classes themselves depend on Flow APIs that do not allow static method calls. To fix this issue, all static utility calls are replaced with instance calls on a utility instance that is injected via dependency injection.
+
.Example: GeneralUtility instance being injected
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
class Foo {
  public function foo($baz) {
    $bar = GeneralUtility::trimExplode(
      $baz);
  }
}
----
|

[source,php]
----
class Foo {
  /** @var GeneralUtility
   *  @Flow\Inject */
  protected $generalUtility;
  public function foo($baz) {
    $bar = $this->generalUtility
      ->trimExplode($baz);
  }
}
----

|===
+
FlashMessageVisitor::
    This visitor fixes some outdated usages of the `FlashMessageContainer` class. Basically, all this visitor does is converting `$this->flashMessages->add('foo')` to `$this->addFlashMessage('foo')`. That's it.

PackageRedirectVisitor::
    This visitor fixes usages of `redirect` method offered by the `ActionController`. Upon calling this method, you can specify an extension key. When this method is called with an extension key, this extension key needs to be replaced with the corresponding TYPO3 Flow package key. This key can easily be retrieved from the _package mapping_, if set. It becomes more difficult, when the extension key parameter is not a string literal, but a dynamic expression. In this case, Metamorph will create a lookup table from the package mapping.
+
.Example: `redirect` call with string literal argument
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
public function fooAction() {
  $this->redirect(
    'show',
    'Controller',
    'my_extension'
  );
}
----
|

[source,php]
----
public function fooAction() {
  $this->redirect(
    'show',
    'Controller',
    'My.Package'
  );
}
----

|===
+
.Example: `redirect` call with dynamic expression argument
[cols="1a,1a"]
|===
|Before | After

|
[source,php]
----
public function fooAction($target) {
  $this->redirect(
    'show',
    'Controller',
    $target
  );
}
----
|

[source,php]
----
public function fooAction($target) {
  $metamorphExtensions = [
    'my_extension' => 'My.Package'
  ];
  $this->redirect(
    'show',
    'Controller',
    $metamorphExtensions[$target]
  );
}
----

|===

=== Locallang transformation

Extbase still allows using locallang XML files for translation handling. This is a TYPO3-proprietary format that is not supported by TYPO3 Flow. These files will be converted into the XLIFF format (which is an OASIS standard). This is done by a XSLT transformation that is executed in the `Mw\Metamorph\Step\MigrateDatabaseStructure` step. Have a look at the XSLT stylesheet in `Resources/Xslt` if you are interested in further details.

=== Database migration

In this step, Metamorph will enrich the migrated domain entity classes by the necessary doctrine annotations. For this, Metamorph parses the source extension's _Table Configuration Array_ (short _TCA_) and extracts all necessary mapping information. Depending on your configuration, the following things will happen:

. The domain models will be extended by Doctrine anntations for http://doctrine-orm.readthedocs.org/en/latest/reference/association-mapping.html[association mapping] (like for example `@ORM\OneToMany(inversedBy="foo")`.
+
.Example on association mapping
****
Consider an entity class `My\Example\Domain\Model\Product` with the following _TCA_:

[source,php]
----
$TCA['tx_example_domain_model_product']['columns']['inventory_changes'] = [
    'config' => [
        'type'          => 'inline',
        'maxitems'      => 9999,
        'foreign_table' => 'tx_example_domain_model_inventorychange',
        'foreign_field' => 'product'
    ]
];
----

IMPORTANT: Remember that Extbase expects database columns to be `under_scored`, and entity attribute names to be `camelCased`. Extbase automatically converts between these two notations, and so does Metamorph. This means that whenever you see a _database column_ like `inventory_changes`, this will be actually mapped to a property named `inventoryChanges`.

Altough it is not specifically labeled as such, an `inline` relation in the TCA is actually a 1:n relation. This relation is stored in the `inventoryChanges` property of the `Product` class. Metamorph would now add the following annotations to this property:

[source,php]
----
class Product {
    /**
     * @ORM\OneToMany(mappedBy="product") // <1>
     * @var Collection<InventoryChange>
     */
    protected $inventoryChanges;
}
----
<1> Here, `product` is the `foreign_field` value from the TCA.

Furthermore, Metamorph will adjust the inverse property, too. Typically, the `InventoryChange` class should have a `product` property.

IMPORTANT: If there is no inverse property for an 1:n relationship, Metamorph will add one!

[source,php]
----
class InventoryChange {
    /**
     * @ORM\ManyToOne(inversedBy="inventoryChanges") // <1>
     * @var Product
     */
    protected $product;
}
----
<1> Here, `inventoryChanges` is the name of the property in the target entity.
****
+
. Optionally, Metamorph will add Doctrine annotations so that table and column names match the old Extbase mapping! This includes adding a `uid` column to all tables and declaring it as identifier.
+
.Example on compatibility mapping
****
Consider the following entity class:

[source,php]
----
/**
 * @Flow\Entity
 */
class Product {
    /**
     * @var string
     */
    protected $longDescription;

    /**
     * @var Collection<InventoryChange>
     * @ORM\OneToMany(mappedBy="product")
     */
    protected $inventoryChanges;
}
----

In compatibility mode, Metamorph would modify this class as follows:

[source,php]
----
/**
 * @Flow\Entity
 * @ORM\Table(name="tx_example_domain_model_product") <1>
 */
class Product {
    /**
     * @var int
     * @Flow\Identity
     * @ORM\GeneratedValue
     */
    protected $uid; // <2>

    /**
     * @var string
     * @ORM\Column(name="long_description") <3>
     */
    protected $longDescription;

    /**
     * @var Collection<InventoryChange>
     * @ORM\OneToMany(mappedBy="product")
     */
    protected $inventoryChanges;
}
----
<1> Here, Metamorph will insert the original table name. Without this annotation, Flow would auto-generate a table name like `my_example_domain_model_product` (note the different namespace).
<2> This attribute is added automatically, because TYPO3 Extbase adds a `uid` column to all entities by convention. The `@Flow\Identity` marks this attribute as the primary key and the `@ORM\GeneratedValue` causes Doctrine to rely on the DBMS' auto-incrementing key. Without this attribute, Flow would auto-generate a `persistence_object_identifier` property with UUID values.
<3> The value `long_description` is loaded from the original TCA. By default, Flow would use `longdescription` as column name.
****

== Further reading

Have a look at the link:TechnicalManual.adoc[technical manual] to learn the architectural concepts behind these transformations and how to add your own transformation to Metamorph's migration process.
